services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend/yolo:/app/yolo
    env_file: ./backend/.env
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    command: >
      sh -c "celery -A app.workers.celery_app beat --loglevel=info &
            celery -A app.workers.inference_worker worker --loglevel=info --pool=threads --concurrency=8"
    env_file: ./backend/.env
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development

volumes:
  pgdata: