"use client";
import { useEffect, useState } from "react";
import { EMISSION_DEFINITIONS } from "@/constants/emissions";
import { fetchSegmentEmission } from "@/services/api";
import { SegmentEmissionDetail } from "@/types";

export default function SegmentPanel({ segmentId, onClose }: { segmentId: string | null; onClose: () => void }) {
    if (!segmentId) return null;
    return <SegmentDetailPanel key={segmentId} segmentId={segmentId} onClose={onClose} />;
}

function SegmentDetailPanel({ segmentId, onClose }: { segmentId: string; onClose: () => void }) {
    const [detail, setDetail] = useState<SegmentEmissionDetail | null>(null);
    const [error, setError] = useState<Error | null>(null);
    useEffect(() => { let mounted = true; fetchSegmentEmission(segmentId).then((value) => mounted && setDetail(value)).catch((err) => mounted && setError(err instanceof Error ? err : new Error("Gagal memuat detail segmen"))); return () => { mounted = false; }; }, [segmentId]);
    return <aside className="monitoring-panel segment-panel"><div className="panel-header"><div className="panel-location-icon">━</div><div className="panel-title"><span>SEGMEN TERPILIH</span><h2>{detail?.name ?? segmentId}</h2></div><button onClick={onClose} className="panel-close" aria-label="Tutup panel segmen">×</button></div>
        <div className="panel-content">{!detail && !error && <div className="segment-state"><span className="loading-spinner" />Memuat detail segmen...</div>}{error && <div className="segment-state error-state"><strong>Data segmen tidak tersedia</strong><span>{error.message}</span></div>}{detail && <><div className="segment-overview"><strong>{detail.road_segment_id}</strong><span>{detail.length_km.toFixed(2)} km</span><b className={`priority-badge priority-${detail.priority ?? "unknown"}`}>{detail.priority ?? "Tidak tersedia"}</b></div><section className="panel-section"><div className="section-heading"><div><span>EMISI SEGMEN</span><small>Nilai agregat dalam g/jam</small></div></div><div className="stat-grid">{EMISSION_DEFINITIONS.map(({ key, label }) => <div className={`stat-card pollutant-${key}`} key={key}><span className="stat-label"><i className="pollutant-dot" />{label}</span><strong className="stat-value">{detail.pollutant_totals_g_h[key] == null ? "N/A" : Number(detail.pollutant_totals_g_h[key]).toFixed(2)}<small>g/hr</small></strong></div>)}</div></section><section className="panel-section"><div className="segment-score"><span>DECISION SCORE</span><strong>{detail.decision_score == null ? "Tidak tersedia" : detail.decision_score.toFixed(3)}</strong></div><p className="criteria-status">Kriteria spasial: {detail.spatial_criteria_status}</p><div className="criteria-grid">{Object.entries(detail.raw_criteria).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value == null ? "N/A" : String(value)}</strong></div>)}</div></section><section className="panel-section"><div className="section-heading"><div><span>VOLUME KENDARAAN</span><small>Agregat per jam</small></div></div><div className="vehicle-summary">{["car", "motorcycle", "bus", "truck"].map((key) => <div key={key}><span>{key}</span><strong>{detail.volume_per_hour[key] == null ? "N/A" : Number(detail.volume_per_hour[key]).toFixed(1)}</strong></div>)}</div></section><section className="panel-section provenance"><span>PERIODE</span><p>{new Date(detail.period_start).toLocaleString("id-ID")} - {new Date(detail.period_end).toLocaleString("id-ID")}</p><span>SUMBER KAMERA</span><p>{Array.isArray(detail.provenance.source_cameras) ? detail.provenance.source_cameras.join(", ") : "Tidak tersedia"}</p><span>KEBIJAKAN AGREGASI</span><p>{String(detail.provenance.aggregation_policy ?? "Tidak tersedia")}</p></section></>}</div></aside>;
}
