"""initial tables

Revision ID: 0a29b1f680b2
Revises: 
Create Date: 2026-05-16 18:57:43.788650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

transactional_ddl = False

# revision identifiers, used by Alembic.
revision: str = '0a29b1f680b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis_topology")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable name for the camera'),
    sa.Column('camera_id', sa.String(length=100), nullable=False, comment='Unique slug used in URLs and code, e.g. atcs_urip_sumoharjo'),
    sa.Column('stream_url', sa.String(length=500), nullable=False, comment='Full HLS .m3u8 stream URL'),
    sa.Column('referer', sa.String(length=255), nullable=True, comment='HTTP Referer header required by the CCTV portal'),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='PostGIS point — POINT(longitude latitude) in WGS84'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Set False to disable without deleting emission history'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', name='uq_cameras_camera_id')
    )
    op.create_index('idx_cameras_location_gist', 'cameras', ['location'], unique=False, postgresql_using='gist')
    op.create_table('emissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='UTC time when the detection cycle ran — set explicitly by worker'),
    sa.Column('car', sa.Integer(), nullable=False),
    sa.Column('motorcycle', sa.Integer(), nullable=False),
    sa.Column('bus', sa.Integer(), nullable=False),
    sa.Column('truck', sa.Integer(), nullable=False),
    sa.Column('total_g_per_min', sa.Float(), nullable=False),
    sa.Column('total_kg_per_hr', sa.Float(), nullable=False),
    sa.Column('cycle_duration_s', sa.Float(), nullable=False, comment='How long the detection cycle took in seconds'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emissions_camera_id_timestamp', 'emissions', ['camera_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emissions_camera_id_timestamp', table_name='emissions')
    op.drop_table('emissions')
    op.drop_index('idx_cameras_location_gist', table_name='cameras', postgresql_using='gist')
    op.drop_table('cameras')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS postgis_topology")
    op.execute("DROP EXTENSION IF EXISTS postgis")
