"""add another emissions column

Revision ID: 402026177317
Revises: 0a29b1f680b2
Create Date: 2026-05-20 22:11:35.685024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402026177317'
down_revision: Union[str, None] = '0a29b1f680b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cameras_location_gist', table_name='cameras', postgresql_using='gist')
    op.add_column('emissions', sa.Column('total_co_g_per_min', sa.Float(), nullable=False))
    op.add_column('emissions', sa.Column('total_co_kg_per_hr', sa.Float(), nullable=False))
    op.add_column('emissions', sa.Column('total_nox_g_per_min', sa.Float(), nullable=False))
    op.add_column('emissions', sa.Column('total_nox_kg_per_hr', sa.Float(), nullable=False))
    op.add_column('emissions', sa.Column('total_pm_g_per_min', sa.Float(), nullable=False))
    op.add_column('emissions', sa.Column('total_pm_kg_per_hr', sa.Float(), nullable=False))
    op.add_column('emissions', sa.Column('total_nmvoc_g_per_min', sa.Float(), nullable=False))
    op.add_column('emissions', sa.Column('total_nmvoc_kg_per_hr', sa.Float(), nullable=False))
    op.drop_column('emissions', 'total_kg_per_hr')
    op.drop_column('emissions', 'total_g_per_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emissions', sa.Column('total_g_per_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('emissions', sa.Column('total_kg_per_hr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('emissions', 'total_nmvoc_kg_per_hr')
    op.drop_column('emissions', 'total_nmvoc_g_per_min')
    op.drop_column('emissions', 'total_pm_kg_per_hr')
    op.drop_column('emissions', 'total_pm_g_per_min')
    op.drop_column('emissions', 'total_nox_kg_per_hr')
    op.drop_column('emissions', 'total_nox_g_per_min')
    op.drop_column('emissions', 'total_co_kg_per_hr')
    op.drop_column('emissions', 'total_co_g_per_min')
    op.create_index('idx_cameras_location_gist', 'cameras', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
