CAMERAS = [
    {
        "name": "ATCS UTARA-TIMUR GARDENA (JL. URIP SUMOHARJO) V. TIMUR",
        "camera_id": "atcs_urip_sumoharjo",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Utara-Timur_Gardena_Jl_Urip%20Sumoharjo_V_Timur.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.381315,
        "latitude": -7.782848,
        "is_active": True,
    },
    {
        "name": "SIMPANG MIROTA (PTZ)",
        "camera_id": "atcs_mirota",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_mirota.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.374343,
        "latitude": -7.776065,
        "is_active": True,
    },
    {
        "name": "SIMPANG BOROBUDUR PLAZA",
        "camera_id": "atcs_borobudur_plaza",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Borobudur_Plaza.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.361052,
        "latitude": -7.778327,
        "is_active": True,
    },
    {
        "name": "SIMPANG KIAI MOJO 1 (BARAT)",
        "camera_id": "atcs_kiai_mojo",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Lampu_Merah_KyaiMojo.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.357921,
        "latitude": -7.78277,
        "is_active": True,
    },
    {
        "name": "SIMPANG TUGU (PTZ)",
        "camera_id": "atcs_tugu",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Tugu.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.367075,
        "latitude": -7.782943,
        "is_active": True,
    },
    {
        "name": "SIMPANG TERBAN VIEW BARAT",
        "camera_id": "atcs_terban_barat",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Terban_View_Barat.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.372358,
        "latitude": -7.782839,
        "is_active": True,
    },
    {
        "name": "SIMPANG GRAMEDIA V. UTARA-TIMUR",
        "camera_id": "atcs_gramedia",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_gramedia.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.374781,
        "latitude": -7.782974,
        "is_active": True,
    },
    {
        "name": "SIMPANG GALERIA (PTZ)",
        "camera_id": "atcs_galeria",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Galeria_TimurSelatan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.379225,
        "latitude": -7.782997,
        "is_active": True,
    },
    {
        "name": "SIMPANG DEMANGAN VIEW UTARA",
        "camera_id": "atcs_demangan_utara",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Demangan_View_Utara.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.387739,
        "latitude": -7.782991,
        "is_active": True,
    },
    {
        "name": "PASAR DEMANGAN VIEW SELATAN",
        "camera_id": "atcs_pasar_demangan_selatan",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Pasar_Demangan_View_Selatan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.388122,
        "latitude": -7.780989,
        "is_active": True,
    },
    {
        "name": "SIMPANG UKDW (PTZ)",
        "camera_id": "atcs_ukdw",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_ukdw.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.378648,
        "latitude": -7.787223,
        "is_active": True,
    },
    {
        "name": "JL. WARDHANI (SELATAN-TIMUR SMPN 5)",
        "camera_id": "kotabaru_wardhani",
        "stream_url": "https://cctvjss.jogjakota.go.id/kotabaru/ANPR-Jl-Wardhani.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.37551,
        "latitude": -7.787385,
        "is_active": True,
    },
    {
        "name": "JL. YOS SUDARSO (MIE GACOAN)",
        "camera_id": "kotabaru_yos_sudarso",
        "stream_url": "https://cctvjss.jogjakota.go.id/kotabaru/ANPR-Jl-Yos-Sudarso.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.374927,
        "latitude": -7.788111,
        "is_active": True,
    },
    {
        "name": "JL. SAJIONO (ROEMI)",
        "camera_id": "kotabaru_sajiono",
        "stream_url": "https://cctvjss.jogjakota.go.id/kotabaru/Jl-Sajiono.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.374401,
        "latitude": -7.785589,
        "is_active": True,
    },
    {
        "name": "JL. F.M. NOTO (GARDU ANIEM)",
        "camera_id": "kotabaru_fm_noto_gardu",
        "stream_url": "https://cctvjss.jogjakota.go.id/kotabaru/ANPR-Jl-FM-Noto-Gardu-Aniem.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.37217,
        "latitude": -7.786836,
        "is_active": True,
    },
    {
        "name": "JL. F.M. NOTO (RAMINTEN)",
        "camera_id": "kotabaru_fm_noto_raminten",
        "stream_url": "https://cctvjss.jogjakota.go.id/kotabaru/ANPR-Jl-FM-Noto-Raminten.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.37161,
        "latitude": -7.784884,
        "is_active": True,
    },
    {
        "name": "UTARA TETEG",
        "camera_id": "margo_utomo_utara_teteg",
        "stream_url": "https://cctvjss.jogjakota.go.id/margo-utomo/Wisma-Ratih.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.366106,
        "latitude": -7.789531,
        "is_active": True,
    },
    {
        "name": "JL. AHMAD JAZULI (APOTEK K24)",
        "camera_id": "kotabaru_ahmad_jazuli",
        "stream_url": "https://cctvjss.jogjakota.go.id/kotabaru/ANPR-Jl-Ahmad-Jazuli.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.369658,
        "latitude": -7.789175,
        "is_active": True,
    },
    {
        "name": "SIMPANG JLAGRAN (PTZ)",
        "camera_id": "atcs_jlagran",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_jlagran.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.357599,
        "latitude": -7.788994,
        "is_active": True,
    },
    {
        "name": "SIMPANG BPK (PTZ)",
        "camera_id": "atcs_bpk",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_bpk.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.353796,
        "latitude": -7.790770,
        "is_active": True,
    },
    {
        "name": "SIMPANG WIROBRAJAN (PTZ)",
        "camera_id": "atcs_wirobrajan",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_wirobrajan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.351744,
        "latitude": -7.80102,
        "is_active": True,
    },
    {
        "name": "SIMPANG PKU MUH. (PTZ)",
        "camera_id": "atcs_pkumuh",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_pkumuh.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.362012,
        "latitude": -7.801285,
        "is_active": True,
    },
    {
        "name": "NOL KM. - TIMUR",
        "camera_id": "malioboro_nol_km_timur",
        "stream_url": "https://cctvjss.jogjakota.go.id/malioboro/NolKm_Timur.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.365097,
        "latitude": -7.801308,
        "is_active": True,
    },
    {
        "name": "MALIOBORO PASAR BERINGHARJO",
        "camera_id": "malioboro_pasar_beringharjo",
        "stream_url": "https://cctvjss.jogjakota.go.id/malioboro/Malioboro_30_Pasar_Beringharjo.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.36503,
        "latitude": -7.798675,
        "is_active": True,
    },
    {
        "name": "MALIOBORO SIMPANG PAJEKSAN SURYATMAJAN",
        "camera_id": "malioboro_pajeksan_suryatmajan",
        "stream_url": "https://cctvjss.jogjakota.go.id/malioboro/Malioboro_22_Simpang_Pajeksan_Suryatmajan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.365356,
        "latitude": -7.796379,
        "is_active": True,
    },
    {
        "name": "MALIOBORO DEPAN DPRD",
        "camera_id": "malioboro_depan_dprd",
        "stream_url": "https://cctvjss.jogjakota.go.id/malioboro/Malioboro_4_Depan_DPRD.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.365913,
        "latitude": -7.792004,
        "is_active": True,
    },
    {
        "name": "MALIOBORO UTARA INNA MALIOBORO",
        "camera_id": "malioboro_utara_inna",
        "stream_url": "https://cctvjss.jogjakota.go.id/malioboro/Malioboro_21_Utara_Inna_Malioboro.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.366212,
        "latitude": -7.790228,
        "is_active": True,
    },
    {
        "name": "SIMPANG GONDOMANAN (PTZ)",
        "camera_id": "atcs_gondomanan",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_gondomanan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.369148,
        "latitude": -7.801699,
        "is_active": True,
    },
    {
        "name": "SIMPANG PERMATA (PTZ)",
        "camera_id": "atcs_permata",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_permata.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.373101,
        "latitude": -7.801559,
        "is_active": True,
    },
    {
        "name": "SIMPANG SENTUL (PTZ)",
        "camera_id": "atcs_sentul",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_sentul.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.377954,
        "latitude": -7.801492,
        "is_active": True,
    },
    {
        "name": "SIMPANG MANDALA KRIDA (PTZ)",
        "camera_id": "atcs_mandala_krida",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Mandala_Krida_PTZ.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.385001,
        "latitude": -7.79765,
        "is_active": True,
    },
    {
        "name": "SIMPANG AMONGROGO VIEW TIMUR",
        "camera_id": "atcs_amongrogo_timur",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Amongrogo_View_Timur.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.383626,
        "latitude": -7.79749,
        "is_active": True,
    },
    {
        "name": "SIMPANG TUNJUNG (PTZ)",
        "camera_id": "atcs_tunjung",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_tunjung.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.377823,
        "latitude": -7.793602,
        "is_active": True,
    },
    {
        "name": "SIMPANG SGM (PTZ)",
        "camera_id": "atcs_sgm",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_simpangsgm.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.395243,
        "latitude": -7.802135,
        "is_active": True,
    },
    {
        "name": "SIMPANG APMD (PTZ)",
        "camera_id": "atcs_apmd",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_apmd.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.391557,
        "latitude": -7.791894,
        "is_active": True,
    },
    {
        "name": "SIMPANG BALAIKOTA VIEW UTARA-BARAT",
        "camera_id": "atcs_balaikota_utara_barat",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Balaikota_View_Timur.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.39231,
        "latitude": -7.799595,
        "is_active": True,
    },
    {
        "name": "SIMPANG REJOWINANGUN VIEW TIMUR",
        "camera_id": "atcs_rejowinangun_timur",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Rejowinangun_View_Timur.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.401981,
        "latitude": -7.810709,
        "is_active": True,
    },
    {
        "name": "SIMPANG GAMBIRAN 2 - JL. VETERAN",
        "camera_id": "atcs_gambiran2",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Lampu_Merah_Gambiran2.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.391666,
        "latitude": -7.814365,
        "is_active": True,
    },
    {
        "name": "SIMPANG GAMBIRAN VIEW BARAT",
        "camera_id": "atcs_gambiran_barat",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Gambiran_View_Barat.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.390704,
        "latitude": -7.817971,
        "is_active": True,
    },
    {
        "name": "SIMPANG APPI 2 - JL. MENTRI SUPENO",
        "camera_id": "atcs_appi2",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Lampu_Merah_JlMentriSupeno2.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.383888,
        "latitude": -7.81666,
        "is_active": True,
    },
    {
        "name": "SIMPANG TUNGKAK (PTZ)",
        "camera_id": "atcs_tungkak",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_tungkak.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.376134,
        "latitude": -7.815719,
        "is_active": True,
    },
    {
        "name": "SIMPANG KARANG TUNGGAL (S3 JL. KOL. SUGIYONO - JL. SISINGAMANGARAJA) 2",
        "camera_id": "atcs_karang_tunggal2",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Lampu_Merah_SopMerah2.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.373163,
        "latitude": -7.815198,
        "is_active": True,
    },
    {
        "name": "SIMPANG JOKTENG WETAN",
        "camera_id": "atcs_jokteng_wetan",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_joktengwetan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.368502,
        "latitude": -7.814715,
        "is_active": True,
    },
    {
        "name": "SIMPANG MANTRIGAWEN (PTZ)",
        "camera_id": "atcs_mantrigawen",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Mantrigawen_PTZ.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.36901,
        "latitude": -7.808856,
        "is_active": True,
    },
    {
        "name": "SIMPANG IBU RUSWO (PTZ)",
        "camera_id": "atcs_ibu_ruswo",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Ibu_Ruswo.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.369282,
        "latitude": -7.803195,
        "is_active": True,
    },
    {
        "name": "SIMPANG PASAR GADING 2 (BARAT)",
        "camera_id": "atcs_pasar_gading2",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Lampu_Merah_PasarGading2.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.362774,
        "latitude": -7.813998,
        "is_active": True,
    },
    {
        "name": "SIMPANG JOKTENG KULON (PTZ)",
        "camera_id": "atcs_jokteng_kulon",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_joktengkulon.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.355963,
        "latitude": -7.812957,
        "is_active": True,
    },
    {
        "name": "SIMPANG TAMAN SARI (PTZ)",
        "camera_id": "atcs_taman_sari",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_tamansari.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.356019,
        "latitude": -7.808616,
        "is_active": True,
    },
    {
        "name": "SIMPANG SUGENG JERONI 2 - JL. SUGENG JERONI",
        "camera_id": "atcs_sugeng_jeroni2",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Lampu_Merah_SugengJeroni2.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.349455,
        "latitude": -7.811919,
        "is_active": True,
    },
    {
        "name": "SIMPANG PATANGPULUHAN (PTZ)",
        "camera_id": "atcs_patangpuluhan",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Patangpuluhan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.350323,
        "latitude": -7.807859,
        "is_active": True,
    },
    {
        "name": "KEMMJ - JALAN SELATAN KEMANTREN",
        "camera_id": "kecamatan_kemmj_selatan",
        "stream_url": "https://cctvjss.jogjakota.go.id/kecamatan/KemMJ-JalanSelatanKemantren.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.361724,
        "latitude": -7.820773,
        "is_active": True,
    },
    {
        "name": "SIMPANG JOGOKARIYAN V. SELATAN",
        "camera_id": "atcs_jogokariyan_selatan",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_jogokaryan.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.367714,
        "latitude": -7.824567,
        "is_active": True,
    },
    {
        "name": "SIMPANG PASAR TELO VIEW UTARA",
        "camera_id": "atcs_pasar_telo_utara",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Pasar_Telo_View_Utara.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.373243,
        "latitude": -7.823929,
        "is_active": True,
    },
    {
        "name": "SIMPANG WIROSABAN VIEW BARAT",
        "camera_id": "atcs_wirosaban_barat",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Wirosaban_View_Barat.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.378438,
        "latitude": -7.824785,
        "is_active": True,
    },
    {
        "name": "SIMPANG TEGALGENDU V. SELATAN",
        "camera_id": "atcs_tegalgendu_selatan",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Tegalgendu.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.390091,
        "latitude": -7.825777,
        "is_active": True,
    },
    {
        "name": "SIMPANG BASEN",
        "camera_id": "atcs_basen",
        "stream_url": "https://cctvjss.jogjakota.go.id/atcs/ATCS_Simpang_Basen.stream/playlist.m3u8",
        "referer": "https://cctv.jogjakota.go.id/",
        "longitude": 110.400797,
        "latitude": -7.820474,
        "is_active": True,
    },

    # {
    #     "name": "",
    #     "camera_id": "",
    #     "stream_url": "",
    #     "referer": "https://cctv.jogjakota.go.id/",
    #     "longitude": 0.0,
    #     "latitude": 0.0,
    #     "is_active": True,
    # },
]